// Total snippets: 13
// -----------------------------------------
// Snippet #0 platforms ffffffff:
Keywords always included into build: FOG_LINEAR FOG_EXP FOG_EXP2 INSTANCING_ON
Builtin keywords used: DIRECTIONAL LIGHTPROBE_SH SHADOWS_SHADOWMASK DYNAMICLIGHTMAP_ON LIGHTMAP_ON LIGHTMAP_SHADOW_MIXING DIRLIGHTMAP_COMBINED SHADOWS_SCREEN VERTEXLIGHT_ON

8 keyword variants used in scene:

DIRECTIONAL
DIRECTIONAL LIGHTPROBE_SH
DIRECTIONAL SHADOWS_SCREEN
DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN
DIRECTIONAL VERTEXLIGHT_ON
DIRECTIONAL LIGHTPROBE_SH VERTEXLIGHT_ON
DIRECTIONAL SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN VERTEXLIGHT_ON


// -----------------------------------------
// Snippet #1 platforms 0013df32:
Keywords always included into build: LIGHTMAP_OFF LIGHTMAP_ON DIRLIGHTMAP_OFF DIRLIGHTMAP_COMBINED DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF DYNAMICLIGHTMAP_ON FOG_LINEAR FOG_EXP FOG_EXP2
Builtin keywords used: DIRECTIONAL LIGHTPROBE_SH SHADOWS_SHADOWMASK DYNAMICLIGHTMAP_ON LIGHTMAP_ON LIGHTMAP_SHADOW_MIXING DIRLIGHTMAP_COMBINED SHADOWS_SCREEN VERTEXLIGHT_ON

24 keyword variants used in scene:

DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF LIGHTPROBE_SH
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF LIGHTPROBE_SH SHADOWS_SCREEN
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF LIGHTPROBE_SH VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF LIGHTPROBE_SH SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF LIGHTPROBE_SH
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF LIGHTPROBE_SH SHADOWS_SCREEN
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF LIGHTPROBE_SH VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF LIGHTPROBE_SH SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF
DIRECTIONAL DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF LIGHTPROBE_SH
DIRECTIONAL DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN
DIRECTIONAL DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF LIGHTPROBE_SH SHADOWS_SCREEN
DIRECTIONAL DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF LIGHTPROBE_SH VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF LIGHTPROBE_SH SHADOWS_SCREEN VERTEXLIGHT_ON


// -----------------------------------------
// Snippet #2 platforms ffffffff:
Keywords always included into build: FOG_LINEAR FOG_EXP FOG_EXP2

1 keyword variants used in scene:

<no keywords defined>


// -----------------------------------------
// Snippet #3 platforms ffffffff:
Keywords always included into build: FOG_LINEAR FOG_EXP FOG_EXP2 INSTANCING_ON
Builtin keywords used: POINT DIRECTIONAL SPOT POINT_COOKIE DIRECTIONAL_COOKIE

5 keyword variants used in scene:

POINT
DIRECTIONAL
SPOT
POINT_COOKIE
DIRECTIONAL_COOKIE


// -----------------------------------------
// Snippet #4 platforms ffffffff:
Keywords always included into build: INSTANCING_ON
Builtin keywords used: SHADOWS_DEPTH SHADOWS_CUBE

2 keyword variants used in scene:

SHADOWS_DEPTH
SHADOWS_CUBE


// -----------------------------------------
// Snippet #5 platforms 0013df32:
Keywords always included into build: LIGHTMAP_OFF LIGHTMAP_ON DIRLIGHTMAP_OFF DIRLIGHTMAP_COMBINED DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF DYNAMICLIGHTMAP_ON FOG_LINEAR FOG_EXP FOG_EXP2
Builtin keywords used: POINT DIRECTIONAL SPOT POINT_COOKIE DIRECTIONAL_COOKIE SHADOWS_SHADOWMASK LIGHTMAP_SHADOW_MIXING SHADOWS_DEPTH SHADOWS_SOFT SHADOWS_SCREEN SHADOWS_CUBE

39 keyword variants used in scene:

DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF
DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SPOT
DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT_COOKIE
DIRECTIONAL_COOKIE DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF
DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_DEPTH SPOT
DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_DEPTH SHADOWS_SOFT SPOT
DIRECTIONAL DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN
DIRECTIONAL_COOKIE DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN
DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT SHADOWS_CUBE
DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT SHADOWS_CUBE SHADOWS_SOFT
DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT_COOKIE SHADOWS_CUBE
DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT_COOKIE SHADOWS_CUBE SHADOWS_SOFT
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SPOT
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT_COOKIE
DIRECTIONAL_COOKIE DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_DEPTH SPOT
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_DEPTH SHADOWS_SOFT SPOT
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN
DIRECTIONAL_COOKIE DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT SHADOWS_CUBE
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT SHADOWS_CUBE SHADOWS_SOFT
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT_COOKIE SHADOWS_CUBE
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT_COOKIE SHADOWS_CUBE SHADOWS_SOFT
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT
DIRECTIONAL DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SPOT
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT_COOKIE
DIRECTIONAL_COOKIE DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_DEPTH SPOT
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_DEPTH SHADOWS_SOFT SPOT
DIRECTIONAL DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN
DIRECTIONAL_COOKIE DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_SCREEN
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT SHADOWS_CUBE
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT SHADOWS_CUBE SHADOWS_SOFT
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT_COOKIE SHADOWS_CUBE
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF POINT_COOKIE SHADOWS_CUBE SHADOWS_SOFT


// -----------------------------------------
// Snippet #6 platforms 0013df32:
Keywords always included into build: LIGHTMAP_OFF LIGHTMAP_ON DIRLIGHTMAP_OFF DIRLIGHTMAP_COMBINED DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF DYNAMICLIGHTMAP_ON FOG_LINEAR FOG_EXP FOG_EXP2
Builtin keywords used: SHADOWS_DEPTH SHADOWS_CUBE

6 keyword variants used in scene:

DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_DEPTH
DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_CUBE
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_DEPTH
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_CUBE
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_DEPTH
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_CUBE


// -----------------------------------------
// Snippet #7 platforms ffffffff:
Keywords always included into build: INSTANCING_ON

1 keyword variants used in scene:

<no keywords defined>


// -----------------------------------------
// Snippet #8 platforms ffffffff:
Keywords always included into build: FOG_LINEAR FOG_EXP FOG_EXP2 POINT SPOT

3 keyword variants used in scene:

<no keywords defined>
POINT
SPOT


// -----------------------------------------
// Snippet #9 platforms ffffffff:
Keywords always included into build: FOG_LINEAR FOG_EXP FOG_EXP2 INSTANCING_ON
Builtin keywords used: LIGHTPROBE_SH DYNAMICLIGHTMAP_ON SHADOWS_SHADOWMASK LIGHTMAP_ON DIRLIGHTMAP_COMBINED UNITY_HDR_ON

4 keyword variants used in scene:

<no keywords defined>
LIGHTPROBE_SH
UNITY_HDR_ON
LIGHTPROBE_SH UNITY_HDR_ON


// -----------------------------------------
// Snippet #10 platforms 0013df32:
Keywords always included into build: LIGHTMAP_OFF LIGHTMAP_ON DIRLIGHTMAP_OFF DIRLIGHTMAP_COMBINED DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF DYNAMICLIGHTMAP_ON FOG_LINEAR FOG_EXP FOG_EXP2
Builtin keywords used: SHADOWS_DEPTH SHADOWS_CUBE

6 keyword variants used in scene:

DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_DEPTH
DIRLIGHTMAP_OFF DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_CUBE
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_DEPTH
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_CUBE
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_DEPTH
DIRLIGHTMAP_SEPARATE DYNAMICLIGHTMAP_OFF LIGHTMAP_OFF SHADOWS_CUBE


// -----------------------------------------
// Snippet #11 platforms fffffbff:
Keywords always included into build: INSTANCING_ON
Builtin keywords used: LIGHTPROBE_SH DYNAMICLIGHTMAP_ON SHADOWS_SHADOWMASK LIGHTMAP_ON DIRLIGHTMAP_COMBINED UNITY_HDR_ON

4 keyword variants used in scene:

<no keywords defined>
LIGHTPROBE_SH
UNITY_HDR_ON
LIGHTPROBE_SH UNITY_HDR_ON


// -----------------------------------------
// Snippet #12 platforms ffffffff:
Keywords stripped away when not used: EDITOR_VISUALIZATION
Keywords always included into build: INSTANCING_ON

1 keyword variants used in scene:

<no keywords defined>


